stages:
- stage: build
  pool:
    name: "On Premise Visual Studio 2017"
  jobs:
  - job: RUNNABUILD
    steps:
    - powershell: |
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
        $jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
        Write-Host "Version with BuildId $jsonVersionWithId";
        Write-Host "Version with BuildId $jsonVersionWithId";
        Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
        Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/FEAT-2401-0111/PS1/BANNER.BANNER -OutFile C:\TEMP\BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/FEAT-2401-0111/PS1/BANNER.BANNER -OutFile BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/FEAT-2401-0111/PS1/BANNER.BANNER -OutFile .\BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile C:\TEMP\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile $PSScriptRoot\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile .\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile C:\TEMP\BOT.PNG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile $PSScriptRoot\BOT.PNG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile .\BOT.PNG
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        .\ADO.PS1
