        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/PS1/BANNER.BANNER -OutFile C:\TEMP\BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/PS1/BANNER.BANNER -OutFile $PSScriptRoot\BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/PS1/BANNER.BANNER -OutFile .\BANNER.BANNER
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile C:\TEMP\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile $PSScriptRoot\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.SVG -OutFile .\BOT.SVG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile C:\TEMP\BOT.PNG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile $PSScriptRoot\BOT.PNG
        iwr -useb https://raw.githubusercontent.com/kckustomac/rpa-devops/main/IMG/BOT.PNG -OutFile .\BOT.PNG
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
        $jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
        Write-Host "Version with BuildId $jsonVersionWithId";
        Write-Host "Version with BuildId $jsonVersionWithId";
        Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
        Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
        $jsonContent = Get-Content -Path project.json -Raw;
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $parsedJson = ConvertFrom-Json $jsonContent;
        ##################################################################################################
        ##################################################################################################
        Write-Host "$PWD";
        Write-Host "$PWD";
        Write-Host "$PSScriptRoot";
        Write-Host "$PSScriptRoot";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        ##################################################################################################
        ##################################################################################################
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###===============================================###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==-------------------------------------------==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  #####################################################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==#################  BEG  ########################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  #####################################################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###===============================================###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "C:\TEMP\BANNER.BANNER | Cyan";  
        Write-Host "C:\TEMP\BANNER.BANNER | White";  
        Write-Host "C:\TEMP\BANNER.BANNER";  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO x            ';  
        cmd.exe /c 'ECHO xx           ';  
        cmd.exe /c 'ECHO xxx          ';  
        cmd.exe /c 'ECHO xxxx         ';  
        cmd.exe /c 'ECHO xxxxx        ';  
        cmd.exe /c 'ECHO xxxxxx       ';  
        cmd.exe /c 'ECHO xxxxxxx      ';  
        cmd.exe /c 'ECHO xxxxxxxx     ';  
        cmd.exe /c 'ECHO xxxxxxx      ';  
        cmd.exe /c 'ECHO xxxxxx       ';  
        cmd.exe /c 'ECHO xxxxx        ';  
        cmd.exe /c 'ECHO xxxx         ';  
        cmd.exe /c 'ECHO xxx          ';  
        cmd.exe /c 'ECHO xx           ';  
        cmd.exe /c 'ECHO x            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO              ';  
        Write-Host "C:\TEMP\BANNER.BANNER | Cyan";  
        Write-Host "C:\TEMP\BANNER.BANNER | White";  
        Write-Host "C:\TEMP\BANNER.BANNER";  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO x            ';  
        cmd.exe /c 'ECHO xx           ';  
        cmd.exe /c 'ECHO xxx          ';  
        cmd.exe /c 'ECHO xxxx         ';  
        cmd.exe /c 'ECHO xxxxx        ';  
        cmd.exe /c 'ECHO xxxxxx       ';  
        cmd.exe /c 'ECHO xxxxxxx      ';  
        cmd.exe /c 'ECHO xxxxxxxx     ';  
        cmd.exe /c 'ECHO xxxxxxx      ';  
        cmd.exe /c 'ECHO xxxxxx       ';  
        cmd.exe /c 'ECHO xxxxx        ';  
        cmd.exe /c 'ECHO xxxx         ';  
        cmd.exe /c 'ECHO xxx          ';  
        cmd.exe /c 'ECHO xx           ';  
        cmd.exe /c 'ECHO x            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO *            ';  
        cmd.exe /c 'ECHO :            ';  
        cmd.exe /c 'ECHO .            ';  
        cmd.exe /c 'ECHO              ';  
        cmd.exe /c 'ECHO              ';  
        Write-Host "C:\TEMP\BANNER.BANNER | Cyan";  
        Write-Host "C:\TEMP\BANNER.BANNER | White";  
        Write-Host "C:\TEMP\BANNER.BANNER";  
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###===============================================###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==-------------------------------------------==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  #####################################################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==#################  END  ########################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  #####################################################  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###===============================================###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ###==                                           ==###  >>C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        function PWSH_HOST1 {
            Write-Host $_ -foreground WHITE 
        }   
        ##  
        ##  
        function PWSH_HOST2 {
            Write-Host $_ -foreground GREEN 
        }   
        ##  
        ##  
        function PWSH_HOST3 {
            process { Write-Host $_ -foreground WHITE }
        }   
        ##  
        ##  
        function PWSH_HOST4 {
            Write-Output C:\TEMP\BANNER.BANNER -foreground Green
        }   
        ##  
        ##  
        function PWSH_HOST5 {
            process {Write-Host $_ -foreground GREEN}
        }   
        ##  
        ##  
        ##  Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        ##  function Test-Output {
        ##      Write-Output "Hello World"
        ##  }
        ##  
        ##  function Test-Output2 {
        ##      Write-Host "Hello World" -foreground Green
        ##  }
        ##  
        ##  function Receive-Output {
        ##      process { Write-Host $_ -foreground Yellow }
        ##  }
        ##  #Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";














        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        function PWSH_HOST1 {
            Write-Host $_ -foreground WHITE 
        }   
        ##  
        ##  
        function PWSH_HOST2 {
            Write-Host $_ -foreground GREEN 
        }   
        ##  
        ##  
        function PWSH_HOST3 {
            process { Write-Host $_ -foreground WHITE }
        }   
        ##  
        ##  
        function PWSH_HOST4 {
            Write-Output C:\TEMP\BANNER.BANNER -foreground Green
        }   
        ##  
        ##  
        function PWSH_HOST5 {
            process {Write-Host $_ -foreground GREEN}
        }   
        ##  
        ##  
        ##  Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        ##  function Test-Output {
        ##      Write-Output "Hello World"
        ##  }
        ##  
        ##  function Test-Output2 {
        ##      Write-Host "Hello World" -foreground Green
        ##  }
        ##  
        ##  function Receive-Output {
        ##      process { Write-Host $_ -foreground Yellow }
        ##  }
        ##  #Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        ##################################################################################################
        ##################################################################################################
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###===============================================###  '
        Write-Host "#####  ###==-------------------------------------------==###  '
        Write-Host "#####  #####################################################  '
        Write-Host "#####  ###==#################  BEG  ########################  '
        Write-Host "#####  #####################################################  '
        Write-Host "#####  ###===============================================###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###===============================================###  '
        Write-Host "#####  ###==-------------------------------------------==###  '
        Write-Host "#####  #####################################################  '
        Write-Host "#####  ###==#################  END  ########################  '
        Write-Host "#####  #####################################################  '
        Write-Host "#####  ###===============================================###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ###==                                           ==###  '
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        function PWSH_HOST1 {
            Write-Host $_ -foreground WHITE 
        }   
        ##  
        ##  
        function PWSH_HOST2 {
            Write-Host $_ -foreground GREEN 
        }   
        ##  
        ##  
        function PWSH_HOST3 {
            process { Write-Host $_ -foreground WHITE }
        }   
        ##  
        ##  
        function PWSH_HOST4 {
            Write-Output C:\TEMP\BANNER.BANNER -foreground Green
        }   
        ##  
        ##  
        function PWSH_HOST5 {
            process {Write-Host $_ -foreground GREEN}
        }   
        ##  
        ##  
        ##  Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        ##  function Test-Output {
        ##      Write-Output "Hello World"
        ##  }
        ##  
        ##  function Test-Output2 {
        ##      Write-Host "Hello World" -foreground Green
        ##  }
        ##  
        ##  function Receive-Output {
        ##      process { Write-Host $_ -foreground Yellow }
        ##  }
        ##  #Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        ##################################################################################################
        ##################################################################################################
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###===============================================###  "; 
        Write-Host "#####  ###==-------------------------------------------==###  "; 
        Write-Host "#####  #####################################################  "; 
        Write-Host "#####  ###==#################  BEG  ########################  "; 
        Write-Host "#####  #####################################################  "; 
        Write-Host "#####  ###===============================================###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "   ._____________.  "; 
        Write-Host "   [_____________]  "; 
        Write-Host "   [ZZZZ-231291A ]  "; 
        Write-Host "   [             ]  "; 
        Write-Host "   [_____________]  "; 
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "   [_____________]  "; 
        Write-Host "   [ZZZZ-231291B ]  "; 
        Write-Host "   [             ]  "; 
        Write-Host "   [_____________]  "; 
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###===============================================###  "; 
        Write-Host "#####  ###==-------------------------------------------==###  "; 
        Write-Host "#####  #####################################################  "; 
        Write-Host "#####  ###==#################  END  ########################  "; 
        Write-Host "#####  #####################################################  "; 
        Write-Host "#####  ###===============================================###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        Write-Host "#####  ###==                                           ==###  "; 
        ##################################################################################################
        ##################################################################################################
        Write-Host "$PWD";
        Write-Host "$PWD";
        Write-Host "$PSScriptRoot";
        Write-Host "$PSScriptRoot";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
        ##################################################################################################
        ##################################################################################################
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "$PWD";
        Write-Host "$PWD";
        function PWSH_HOST1 {
            Write-Host $_ -foreground WHITE 
        }   
        ##  
        ##  
        function PWSH_HOST2 {
            Write-Host $_ -foreground GREEN 
        }   
        ##  
        ##  
        function PWSH_HOST3 {
            process { Write-Host $_ -foreground WHITE }
        }   
        ##  
        ##  
        function PWSH_HOST4 {
            Write-Output C:\TEMP\BANNER.BANNER -foreground Green
        }   
        ##  
        ##  
        function PWSH_HOST5 {
            process {Write-Host $_ -foreground GREEN}
        }   
        PWSH_HOST2 | PWSH_HOST5
        PWSH_HOST4
        Write-Host "$PWD";
        Write-Host "$env:PWSH_HOST4";
        Write-Host "$env:PWSH_HOST4";
        Write-Host $PWSH_HOST4
        Write-Host $PWSH_HOST4
        ##  
        ##  
        ##  Output piped to another function, not displayed in first.
        ##  PWSH_HOST2 | PWSH_HOST5
        ##  
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        ##  function Test-Output {
        ##      Write-Output "Hello World"
        ##  }
        ##  
        ##  function Test-Output2 {
        ##      Write-Host "Hello World" -foreground Green
        ##  }
        ##  
        ##  function Receive-Output {
        ##      process { Write-Host $_ -foreground Yellow }
        ##  }
        ##  #Output piped to another function, not displayed in first.
        ##  Test-Output | Receive-Output
        ##  #Output not piped to 2nd function, only displayed in first.
        ##  Test-Output2 | Receive-Output 
        ##  #Pipeline sends to Out-Default at the end.
        ##  Test-Output 
        ##  Y
        ##  
        ##  
        Write-Host "#####  ";
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        CMD.EXE /C 'TYPE C:\TEMP\BANNER.BANNER'
        Write-Host "#####  ";
        Write-Host "#####  #####################################################";
        Write-Host "#####  #####################################################";
        Write-Host "#####  ";
        Write-Host "#####  ";
