parameters:
  - name: orchestratorFolder
    type: string
    default: SHARED
stages:
- stage: build
  pool:
    name: "On Premise Visual Studio 2017"
  jobs:
  - job: secure_buildjob
    steps:
    - powershell: |
        $jsonContent = Get-Content -Path project.json -Raw;
        $parsedJson = ConvertFrom-Json $jsonContent;
        $jsonVersion = $parsedJson.projectVersion;
        Write-Host "Parsed Version $jsonVersion";
        $jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
        Write-Host "Version with BuildId $jsonVersionWithId";
        Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
        Write-Host $PWD
        ECHO 'PSSCRIPTROOT:::' $PSScriptRoot
        $ROOTPATH=($pwd).path
        CD /
        CD $ROOTPATH
        PWD
        CLS

        function Cyan
        {
            process { Write-Host $_ -ForegroundColor Cyan }
        }

        function White
        {
            process { Write-Host $_ -ForegroundColor White }
        }

        $BANNER = [System.IO.File]::ReadAllLines('$ROOTPATH\BANNER.BANNER')

        Write-Output $BANNER | Cyan
        Write-Output $BANNER | White
        Write-Host $ROOTPATH\BANNER.BANNER

        Get-Content $PSScriptRoot\BANNER.BANNER -Tail 10
        Get-Content $PSScriptRoot\BANNER.BANNER -Tail 10 | Cyan
        Get-Content $PSScriptRoot\BANNER.BANNER -Tail 10 | White
        ECHO $ROOTPATH
        ECHO '$ROOTPATH'
        Write-Output $ROOTPATH
        Write-Output '$ROOTPATH'
