$jsonContent = Get-Content -Path project.json -Raw;
$parsedJson = ConvertFrom-Json $jsonContent;
$jsonVersion = $parsedJson.projectVersion;
Write-Host "Parsed Version $jsonVersion";
$jsonVersionWithId = "$jsonVersion.$ENV:BUILD_BUILDID";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ##################################################### ";
Write-Host "#####  ##################################################### ";
Write-Host "Version with BuildId $jsonVersionWithId";
Write-Host "##vso[task.setvariable variable=uiPathProjectVersion]$jsonVersionWithId";
Write-Host $PWD
ECHO $PSScriptRoot
$ROOTPATH=($pwd).path
CLS
CLS
CD /
CD /
CD $ROOTPATH
CLS
CLS
CD /
CD /
CD $ROOTPATH
CD $ROOTPATH
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  BEG  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '@ECHO OFF >D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'

Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '@ECHO OFF >D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";



CLS
CLS
CD /
CD /
CD $ROOTPATH
CLS
CLS
CD /
CD /
CD $ROOTPATH
CD $ROOTPATH
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  BEG  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '@ECHO OFF >D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";


Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '@ECHO OFF >D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO.  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";







cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  END  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
CLS
CLS
CD /
CD /
CD $ROOTPATH
CLS
CLS
CD /
CD /
CD $ROOTPATH
CD $ROOTPATH
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  BEG  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c 'ECHO    ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███████╗██████╗ ██████╗ ██╗███╗   ██╗ ██████╗  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO    ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██║████╗  ██║██╔════╝  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO    ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ███████╗██████╔╝██████╔╝██║██╔██╗ ██║██║  ███╗ >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO    ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ╚════██║██╔═══╝ ██╔══██╗██║██║╚██╗██║██║   ██║ >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO    ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ███████║██║     ██║  ██║██║██║ ╚████║╚██████╔╝ >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO    ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  END  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
CLS
CLS
CD /
CD /
CD $ROOTPATH
CD $ROOTPATH
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  BEG  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
function Cyan
{
process { Write-Host $_ -ForegroundColor Cyan }
}
function White
{
process { Write-Host $_ -ForegroundColor White }
}
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
CD /
CD /
CLS
CLS
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "   ._____________.  "; 
Write-Host "   [_____________]  "; 
Write-Host "   [ZZZZ-231291A ]  "; 
Write-Host "   [             ]  "; 
Write-Host "   [_____________]  "; 
Write-Host "#####  ";
Write-Host "#####  ";
$BANNER = [System.IO.File]::ReadAllLines('D:\a\_temp\BANNER.BANNER')
Write-Host "$BANNER | Cyan  "; 
Write-Host "$BANNER | White  "; 
Write-Host D:\a\_temp\BANNER.BANNER
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
CD /
CLS
CD /
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "   [_____________]  "; 
Write-Host "   [ZZZZ-231291B ]  "; 
Write-Host "   [             ]  "; 
Write-Host "   [_____________]  "; 
Write-Host "#####  ";
Write-Host "#####  ";
$BANNER = [System.IO.File]::ReadAllLines('D:\a\_temp\BANNER.BANNER')
Write-Host D:\a\_temp\$BANNER | Cyan
Write-Host D:\a\_temp\$BANNER | White
Write-Host D:\a\_temp\BANNER.BANNER
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  END  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
CLS
CLS
CD /
CD /
CD $ROOTPATH
CD $ROOTPATH
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  BEG  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
function Cyan
{
process { Write-Host $_ -ForegroundColor Cyan }
}
function White
{
process { Write-Host $_ -ForegroundColor White }
}
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
CD /
CD /
CLS
CLS
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "   ._____________.  "; 
Write-Host "   [_____________]  "; 
Write-Host "   [ZZZZ-231292A ]  "; 
Write-Host "   [             ]  "; 
Write-Host "   [_____________]  "; 
Write-Host "#####  ";
Write-Host "#####  ";
$BANNER = [System.IO.File]::ReadAllLines('D:\a\_temp\BANNER.BANNER')
Write-Host "$BANNER | Cyan  "; 
Write-Host "$BANNER | White  "; 
Write-Host D:\a\_temp\BANNER.BANNER
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
CD /
CLS
CD /
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "   [_____________]  "; 
Write-Host "   [ZZZZ-231292B ]  "; 
Write-Host "   [             ]  "; 
Write-Host "   [_____________]  "; 
Write-Host "#####  ";
Write-Host "#####  ";
$BANNER = [System.IO.File]::ReadAllLines('D:\a\_temp\BANNER.BANNER')
Write-Host D:\a\_temp\$BANNER | Cyan
Write-Host D:\a\_temp\$BANNER | White
Write-Host D:\a\_temp\BANNER.BANNER
Write-Host "#####  ";
Write-Host "#####  #####################################################";
Write-Host "#####  #####################################################";
Write-Host "#####  ";
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==-------------------------------------------==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==#################  END  ########################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  #####################################################  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c 'ECHO   ###_______________________________________________###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  ###==                                           ==###  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'
cmd.exe /c '#####  >>D:\a\_temp\BANNER.BANNER'

