CD 'C:\'
CD 'C:\'
CMD /C 'SETX JTKC__TEMP C:\TEMP'
CMD /C 'SETX JTKC__WORKPATH C:\TEMP'
CMD /C 'SETX XXJTXX C:\TEMP'
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
$XXJTXX = "$env:JTKC__WORKPATH";
Write-Host "$XXJTXX"; 
$XXJTXX = "$env:XXJTXX";
Write-Host "$XXJTXX"; 
$JTKC__WORKPATH = "$env:JTKC__TEMP";
Write-Host "$JTKC__WORKPATH"; 
$JTKC__WORKPATH = "$env:JTKC__WORKPATH";
Write-Host "$JTKC__WORKPATH"; 
$JTKC__WORKPATH = "$env:XXJTXX";
Write-Host "$JTKC__WORKPATH"; 
Write-Host "$env:JTKC__TEMP";
Write-Host "$env:JTKC__WORKPATH";
Write-Host "$env:XXJTXX";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";

$BANNER = [System.IO.File]::ReadAllLines('C:\TEMP\BANNER.BANNER')
$BANNER = [System.IO.File]::ReadAllLines('C:\TEMP\BANNER.BANNER')
Write-Host C:\TEMP\$BANNER | Cyan
Write-Host C:\TEMP\$BANNER | White
Write-Host C:\TEMP\BANNER.BANNER
Write-Host "C:\TEMP\$BANNER | Cyan"; 
Write-Host "C:\TEMP\$BANNER | White"; 
Write-Host "C:\TEMP\BANNER.BANNER"; 


Write-Host C:\TEMP\$BANNER | Cyan
Write-Host C:\TEMP\$BANNER | White
Write-Host C:\TEMP\BANNER.BANNER
Write-Host "C:\TEMP\$BANNER | Cyan"; 
Write-Host "C:\TEMP\$BANNER | White"; 
Write-Host "C:\TEMP\BANNER.BANNER"; 



















CD 'C:\'
CD 'C:\'
CMD /C 'SETX JTKC__TEMP C:\TEMP /M'
CMD /C 'SETX JTKC__TEMP """" /M'
CMD /C 'SETX JTKC__TEMP ""'
CMD /C 'SETX JTKC__TEMP """"'
CMD /C 'SETX JTKC__TEMP C:\TEMP'
CMD /C 'SETX JTKC__TEMP "C:\TEMP'


CD 'C:\'
CD 'C:\'
CMD /C 'SETX JTKC__TEMP C:\TEMP /M'
CMD /C 'SETX JTKC__TEMP """" /M'
CMD /C 'SETX JTKC__TEMP ""'
CMD /C 'SETX JTKC__TEMP """"'
CMD /C 'SETX JTKC__TEMP C:\TEMP'
CMD /C 'SETX JTKC__TEMP "C:\TEMP'


$XXJTXX = "";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 








$XXJTXX = "";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 








CD 'C:\'
CD 'C:\'
CMD /C 'SETX JTKC__TEMP C:\TEMP /M'
CMD /C 'SETX JTKC__TEMP """" /M'
CMD /C 'SETX JTKC__TEMP ""'
CMD /C 'SETX JTKC__TEMP """"'
CMD /C 'SETX JTKC__TEMP C:\TEMP'
CMD /C 'SETX JTKC__TEMP "C:\TEMP'


CD 'C:\'
CD 'C:\'
CMD /C 'SETX JTKC__TEMP C:\TEMP /M'
CMD /C 'SETX JTKC__TEMP """" /M'
CMD /C 'SETX JTKC__TEMP ""'
CMD /C 'SETX JTKC__TEMP """"'
CMD /C 'SETX JTKC__TEMP C:\TEMP'
CMD /C 'SETX JTKC__TEMP "C:\TEMP'


$XXJTXX = "";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 








$XXJTXX = "";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 
$XXJTXX = "$env:JTKC__TEMP";
Write-Host "$XXJTXX"; 
Write-Host "`$XXJTXX :: $XXJTXX"; 






















$XXJTXX = "$env:JTKC__TEMP";
$XXJTXX = "$env:JTKC__WORKPATH";
Write-Host "$XXJTXX"; 
$XXJTXX = "$env:XXJTXX";
Write-Host "$XXJTXX"; 
$JTKC__WORKPATH = "$env:JTKC__TEMP";
Write-Host "$JTKC__WORKPATH"; 
$JTKC__WORKPATH = "$env:JTKC__WORKPATH";
Write-Host "$JTKC__WORKPATH"; 
$JTKC__WORKPATH = "$env:XXJTXX";
Write-Host "$JTKC__WORKPATH"; 
Write-Host "$env:JTKC__TEMP";
Write-Host "$env:JTKC__WORKPATH";
Write-Host "$env:XXJTXX";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";
Write-Host "#####  ";

$BANNER = [System.IO.File]::ReadAllLines('C:\TEMP\BANNER.BANNER')
$BANNER = [System.IO.File]::ReadAllLines('C:\TEMP\BANNER.BANNER')
Write-Host C:\TEMP\$BANNER | Cyan
Write-Host C:\TEMP\$BANNER | White
Write-Host C:\TEMP\BANNER.BANNER
Write-Host "C:\TEMP\$BANNER | Cyan"; 
Write-Host "C:\TEMP\$BANNER | White"; 
Write-Host "C:\TEMP\BANNER.BANNER"; 


Write-Host C:\TEMP\$BANNER | Cyan
Write-Host C:\TEMP\$BANNER | White
Write-Host C:\TEMP\BANNER.BANNER
Write-Host "C:\TEMP\$BANNER | Cyan"; 
Write-Host "C:\TEMP\$BANNER | White"; 
Write-Host "C:\TEMP\BANNER.BANNER"; 
